# Generated by Django 5.1.6 on 2025-02-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
