# Generated by Django 5.1.6 on 2025-02-09 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diagnosis_admission_date_diagnosis_discharge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.appointment'),
            preserve_default=False,
        ),
    ]
