# Generated by Django 5.1.6 on 2025-02-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_insight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availability',
        ),
    ]
