# Generated by Django 5.1.6 on 2025-03-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_doctor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='appointment',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.appointment'),
            preserve_default=False,
        ),
    ]
