# Generated by Django 5.1.6 on 2025-03-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_insight_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='appointment',
        ),
    ]
